# Generated by Django 5.2.12 on 2026-03-31 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0002_agentcibilpricing_planusage_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='bank_verify_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rechargeplan',
            name='gst_verify_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rechargeplan',
            name='pan_verify_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentcibilpricing',
            name='service',
            field=models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF'), ('prefill', 'Prefill'), ('pan_verify', 'PAN Verify'), ('gst_verify', 'GST Verify'), ('bank_verify', 'Bank Verify')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentcibilpricing',
            index=models.Index(fields=['agent', 'service'], name='cibil_agent_agent_i_f0f917_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcibilpricing',
            index=models.Index(fields=['customer'], name='cibil_agent_custome_8b2fa5_idx'),
        ),
    ]
