# Generated by Django 5.2.12 on 2026-04-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0004_planusage_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='aadhaar_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
