# Generated by Django 5.2.12 on 2026-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0005_rechargeplan_aadhaar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcibilpricing',
            name='service',
            field=models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF'), ('prefill', 'Prefill'), ('aadhaar_verify', 'Aadhaar Verify'), ('pan_verify', 'PAN Verify'), ('gst_verify', 'GST Verify'), ('bank_verify', 'Bank Verify')], max_length=20),
        ),
    ]
