# Generated by Django 5.2.12 on 2026-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0006_alter_agentcibilpricing_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='planusage',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
