# Generated by Django 5.2.12 on 2026-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0007_planusage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='cibil_advanced_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rechargeplan',
            name='only_score_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentcibilpricing',
            name='service',
            field=models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF'), ('prefill', 'Prefill'), ('aadhaar_verify', 'Aadhaar Verify'), ('pan_verify', 'PAN Verify'), ('gst_verify', 'GST Verify'), ('bank_verify', 'Bank Verify'), ('cibil_advanced', 'Cibil Advanced'), ('only_score', 'Only Score Check')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cibilreport',
            name='report_type',
            field=models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF'), ('prefill', 'Prefill'), ('cibil_advanced', 'CIBIL Advanced'), ('only_score', 'Only Score')], max_length=20, null=True),
        ),
    ]
