# Generated by Django 5.2.12 on 2026-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibil', '0008_rechargeplan_cibil_advanced_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='leegality_esign_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rechargeplan',
            name='mobile360_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentcibilpricing',
            name='service',
            field=models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('equifax', 'Equifax'), ('crif', 'CRIF'), ('prefill', 'Prefill'), ('aadhaar_verify', 'Aadhaar Verify'), ('pan_verify', 'PAN Verify'), ('gst_verify', 'GST Verify'), ('bank_verify', 'Bank Verify'), ('cibil_advanced', 'Cibil Advanced'), ('only_score', 'Only Score Check'), ('mobile360', 'Mobile360'), ('leegality_esign', 'Leegality eSign')], max_length=20),
        ),
    ]
