# Generated by Django 5.2.12 on 2026-05-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeegalityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=255)),
                ('document_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('irn', models.CharField(db_index=True, max_length=255, unique=True)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_phone', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('sign_url', models.TextField(blank=True, null=True)),
                ('signed_pdf_url', models.TextField(blank=True, null=True)),
                ('audit_trail_url', models.TextField(blank=True, null=True)),
                ('used_signature_type', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_status', models.CharField(default='PENDING', max_length=255)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esign_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
