# Generated by Django 5.2.12 on 2026-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_leegalitydocument_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leegalitydocument',
            name='completion_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leegalitydocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=50),
        ),
    ]
