# Generated by Django 5.2.11 on 2026-03-06 09:14

import django.db.models.deletion
import loans.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_partnerapplication'),
        ('customer', '0002_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png', max_length=100)),
                ('max_size_mb', models.PositiveIntegerField(default=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_loans', to='loans.loantype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='agent.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='customer.customer')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.documenttype')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='loans.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('pincode', models.CharField(max_length=6)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.CharField(choices=[('CC', 'Credit Card'), ('PL', 'Personal Loan'), ('BL', 'Business Loan'), ('IL', 'Insurance Lead'), ('SA', 'Savings Account')], db_index=True, max_length=5)),
                ('reference_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('paysprint_lead_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='INITIATED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('executive_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('executive_updated_date', models.DateTimeField(blank=True, null=True)),
                ('executive_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='loans_credi_agent_i_d19b1c_idx'), models.Index(fields=['mobile'], name='loans_credi_mobile_db4421_idx'), models.Index(fields=['reference_id'], name='loans_credi_referen_bcf0d4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['INITIATED', 'SUBMITTED', 'PENDING'])), fields=('mobile', 'status'), name='prevent_duplicate_active_leads')],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=loans.models.loan_document_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.documenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['is_verified'], name='loans_loand_is_veri_52b37e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='loans_loana_status_ff4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['created_at'], name='loans_loana_created_c0719a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loantypedocument',
            unique_together={('loan_type', 'document_type')},
        ),
    ]
