# Generated by Django 5.2.11 on 2026-03-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_add_product_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardlead',
            name='product',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PL', 'Personal Loan'), ('BL', 'Business Loan'), ('IL', 'Insurance Lead'), ('SA', 'Savings Account')], db_index=True, max_length=5),
        ),
    ]
