# Generated by Django 5.2.11 on 2026-03-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_partnerapplication'),
        ('loans', '0004_alter_creditcardlead_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('category_id', models.CharField(max_length=200)),
                ('bank_id', models.CharField(max_length=200)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_lead_id', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('SENT', 'SENT'), ('PROCESSING', 'PROCESSING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DISBURSED', 'DISBURSED'), ('FAILED', 'FAILED')], default='CREATED', max_length=50)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agent.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
