# Generated by Django 5.2.11 on 2026-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlead',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
