# Generated by Django 5.2.11 on 2026-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanlead_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlead',
            name='application_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanlead',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanlead',
            name='existing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanlead',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanlead',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanlead',
            name='telecaller_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanlead',
            name='provider_lead_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loanlead',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SENT', 'SENT'), ('PROCESSING', 'PROCESSING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SANCTIONED', 'SANCTIONED'), ('DISBURSED', 'DISBURSED'), ('FAILED', 'FAILED')], default='CREATED', max_length=50),
        ),
    ]
