# Generated by Django 5.2.11 on 2026-03-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanlead_application_no_loanlead_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantypedocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='application',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='loantypedocument',
            name='loan_type',
        ),
        migrations.AlterUniqueTogether(
            name='loantypedocument',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='CreditCardLead',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanDocument',
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
        migrations.DeleteModel(
            name='LoanTypeDocument',
        ),
    ]
