# Generated by Django 5.2.11 on 2026-03-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_partnerapplication'),
        ('customer', '0002_customer_user'),
        ('loans', '0008_remove_loantypedocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropelldWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('application_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moratorium', models.IntegerField(default=0)),
                ('course_id', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('propelld_quote_id', models.CharField(blank=True, max_length=200, null=True)),
                ('propelld_application_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUOTE_CREATED', 'Quote Created'), ('APPLIED', 'Applied'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='CREATED', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='agent.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loans.loanapplication')),
            ],
        ),
    ]
