# Generated by Django 5.2.11 on 2026-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_propelldwebhooklog_loanapplication_loanstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlead',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
