# Generated by Django 5.2.11 on 2026-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loanlead_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('SVATANTR', 'Svatantr')], max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
