# Generated by Django 5.2.12 on 2026-03-27 10:07

import django.db.models.deletion
import eduloans.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_partnerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleCaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLoanApplication',
            fields=[
                ('loan_type', models.CharField(choices=[('domestic', 'Domestic'), ('abroad', 'Abroad')], default='domestic', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_executive', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('co_applicant_type', models.CharField(choices=[('none', 'No Co-applicant'), ('business', 'Business'), ('agriculture', 'Agriculture'), ('salaried', 'Salaried'), ('pension', 'Pension'), ('others', 'Others')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_loans', to='agent.agent')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduloans.telecaller')),
            ],
        ),
        migrations.CreateModel(
            name='CoApplicantBankCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('is_verified', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_check', to='eduloans.educationloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('business', 'Business'), ('agriculture', 'Agriculture'), ('salaried', 'Salaried'), ('pension', 'Pension'), ('others', 'Others')], max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('pan', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cibil_score', models.IntegerField(blank=True, null=True)),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('itr', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('land_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('ppo', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('gst', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('business_photos', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('business_address_proof', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('business_address', models.CharField(blank=True, max_length=300, null=True)),
                ('office_address', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coapplicant', to='eduloans.educationloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='HusbandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('father_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('mother_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('marriage_certificate', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='eduloans.educationloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_father', models.CharField(blank=True, max_length=200, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('loan_on_property', models.BooleanField(default=False)),
                ('loan_details', models.CharField(blank=True, max_length=200, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('rural', 'Rural'), ('city', 'City')], max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='eduloans.educationloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('passport', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('study_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('mother_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('father_docs', models.FileField(blank=True, null=True, upload_to=eduloans.utils.education_upload_path)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('grandmother', models.CharField(blank=True, max_length=100, null=True)),
                ('granny', models.CharField(blank=True, max_length=100, null=True)),
                ('ref1', models.CharField(blank=True, max_length=200, null=True)),
                ('ref2', models.CharField(blank=True, max_length=200, null=True)),
                ('cibil_score', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='eduloans.educationloanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurepassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduloans.educationloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_cibil', models.BooleanField(default=False)),
                ('co_cibil', models.BooleanField(default=False)),
                ('bank_verified', models.BooleanField(default=False)),
                ('pan_verified', models.BooleanField(default=False)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('itr_verified', models.BooleanField(default=False)),
                ('msme_verified', models.BooleanField(default=False)),
                ('gst_verified', models.BooleanField(default=False)),
                ('consent_verified', models.BooleanField(default=False)),
                ('education_verified', models.BooleanField(default=False)),
                ('final_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='eduloans.educationloanapplication')),
            ],
        ),
    ]
